// <auto-generated />
using System;
using Norebase_Like_Feature_Challenge.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Norebase_Like_Feature_Challenge.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241105062207_SeedMigration")]
    partial class SeedMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Norebase_Like_Feature_Challenge.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 11, 5, 7, 22, 7, 56, DateTimeKind.Local).AddTicks(7895),
                            LikeCount = 5,
                            Title = "Exploring the Future of Cryptocurrency in Nigeria"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 11, 5, 7, 22, 7, 56, DateTimeKind.Local).AddTicks(7911),
                            LikeCount = 5,
                            Title = "IoT: Transforming Smart Homes in Urban Nigeria"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2024, 11, 5, 7, 22, 7, 56, DateTimeKind.Local).AddTicks(7912),
                            LikeCount = 5,
                            Title = "Cloud Computing: A Game Changer for Nigerian Startups"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2024, 11, 5, 7, 22, 7, 56, DateTimeKind.Local).AddTicks(7913),
                            LikeCount = 5,
                            Title = "Artificial Intelligence and its Impact on Nigeria’s Economy"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2024, 11, 5, 7, 22, 7, 56, DateTimeKind.Local).AddTicks(7947),
                            LikeCount = 5,
                            Title = "The Role of Blockchain Technology in Enhancing Security"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2024, 11, 5, 7, 22, 7, 56, DateTimeKind.Local).AddTicks(7948),
                            LikeCount = 5,
                            Title = "Cybersecurity Trends: Safeguarding Data in the Digital Age"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2024, 11, 5, 7, 22, 7, 56, DateTimeKind.Local).AddTicks(7949),
                            LikeCount = 5,
                            Title = "The Rise of Fintech: Innovations Shaping the Banking Sector"
                        });
                });

            modelBuilder.Entity("Norebase_Like_Feature_Challenge.Domain.Entities.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8123),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 2,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8124),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 3,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8125),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            ArticleId = 4,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8126),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            ArticleId = 5,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8126),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            ArticleId = 1,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8127),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            ArticleId = 3,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8128),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            ArticleId = 4,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8129),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            ArticleId = 5,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8129),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            ArticleId = 6,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8130),
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            ArticleId = 1,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8131),
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            ArticleId = 2,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8131),
                            UserId = 3
                        },
                        new
                        {
                            Id = 13,
                            ArticleId = 3,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8132),
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            ArticleId = 4,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8132),
                            UserId = 3
                        },
                        new
                        {
                            Id = 15,
                            ArticleId = 5,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8133),
                            UserId = 3
                        },
                        new
                        {
                            Id = 16,
                            ArticleId = 7,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8134),
                            UserId = 3
                        },
                        new
                        {
                            Id = 17,
                            ArticleId = 1,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8134),
                            UserId = 4
                        },
                        new
                        {
                            Id = 18,
                            ArticleId = 2,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8135),
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            ArticleId = 6,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8136),
                            UserId = 4
                        },
                        new
                        {
                            Id = 20,
                            ArticleId = 7,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8136),
                            UserId = 4
                        },
                        new
                        {
                            Id = 21,
                            ArticleId = 5,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8137),
                            UserId = 4
                        },
                        new
                        {
                            Id = 22,
                            ArticleId = 3,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8138),
                            UserId = 5
                        },
                        new
                        {
                            Id = 23,
                            ArticleId = 4,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8139),
                            UserId = 5
                        },
                        new
                        {
                            Id = 24,
                            ArticleId = 6,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8139),
                            UserId = 5
                        },
                        new
                        {
                            Id = 25,
                            ArticleId = 1,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8140),
                            UserId = 5
                        },
                        new
                        {
                            Id = 26,
                            ArticleId = 7,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8141),
                            UserId = 5
                        },
                        new
                        {
                            Id = 27,
                            ArticleId = 2,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8141),
                            UserId = 6
                        },
                        new
                        {
                            Id = 28,
                            ArticleId = 3,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8142),
                            UserId = 6
                        },
                        new
                        {
                            Id = 29,
                            ArticleId = 4,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8143),
                            UserId = 6
                        },
                        new
                        {
                            Id = 30,
                            ArticleId = 5,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8143),
                            UserId = 6
                        },
                        new
                        {
                            Id = 31,
                            ArticleId = 6,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8144),
                            UserId = 6
                        },
                        new
                        {
                            Id = 32,
                            ArticleId = 7,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8144),
                            UserId = 6
                        },
                        new
                        {
                            Id = 33,
                            ArticleId = 1,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8145),
                            UserId = 7
                        },
                        new
                        {
                            Id = 34,
                            ArticleId = 2,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8147),
                            UserId = 7
                        },
                        new
                        {
                            Id = 35,
                            ArticleId = 5,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8147),
                            UserId = 7
                        },
                        new
                        {
                            Id = 36,
                            ArticleId = 6,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8148),
                            UserId = 7
                        },
                        new
                        {
                            Id = 37,
                            ArticleId = 7,
                            LikedAt = new DateTime(2024, 11, 5, 6, 22, 7, 56, DateTimeKind.Utc).AddTicks(8149),
                            UserId = 7
                        });
                });

            modelBuilder.Entity("Norebase_Like_Feature_Challenge.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chinedu Okafor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Amaka Nwankwo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Emeka Ibe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ngozi Nwosu"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tunde Adebayo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sola Bakare"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Adaobi Eze"
                        });
                });

            modelBuilder.Entity("Norebase_Like_Feature_Challenge.Domain.Entities.Like", b =>
                {
                    b.HasOne("Norebase_Like_Feature_Challenge.Domain.Entities.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Norebase_Like_Feature_Challenge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
